kind: PersistentVolume
apiVersion: v1
metadata:
  name: research-pvc
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/research-vol"
